server:
  port: 8899
  tomcat:
    accesslog:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/lx_appmodule?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lx_appmodule
    password: o4LJw001ZI6lw3wx
  thymeleaf:
    # 开启视图解析
    enabled: true
    #编码格式
    encoding: UTF-8
    #前缀配置
    prefix: classpath:/templates/
    # 后缀配置
    suffix: .html
    #是否使用缓存 开发环境时不设置缓存
    cache: false
    # 格式为 HTML 格式
    mode: HTML5
    # 配置类型
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.xwlin.entity
logging:
  level:
    org:
      apache:
        tomcat: DEBUG
        catalina: DEBUG