server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://db.xwlin.cn:31431/my_ship?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: LIAOxiang941229