server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.109.56.234:3306/config_center?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LIAOxiang941229
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.xwlin.entity
