server:
  port: 81
spring:
  datasource:
    url: jdbc:mysql://47.109.56.234:3306/school?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: LIAOxiang941229
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.xwlin.majiaxueyuan.entity