server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/liaoxiang?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: liaoxiang
    password: 6401679d4fa6a2b5
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: per.lx.entity
wx:
  miniapp:
    aesKey: '@aesKey'
    appid: wx69c193871872abd7
    msgDataFormat: JSON
    secret: 5571f65dcdb28dc1853ce01d26a6ac39
    token: '@token'
