server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  secret:
    key: majiaxueyuan
logging:
  level:
    per.lx.controller: debug
spring:
  redis:
    host: 1_39a859fe4d25.c.methodot.com
    port: 31581
    database: 0
    username: default
    password: EXvBawuiYuWvhMYxH1vbLWSMZgS4YwN8
    client-type: lettuce
    lettuce:
      pool:
        max-active: 5
        max-wait: 2
        min-idle: 2
        enabled: true