server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  secret:
    key: majiaxueyuan
logging:
  level:
    per.lx.controller: debug
spring:
  redis:
    host: 127.0.0.1
    port: 6379