server:
  port: 8083

spring:
  rabbitmq:
    addresses: gerbil-01.rmq.cloudamqp.com:5672
    connection-timeout: 15000
    password: Z5sHJ1jgcw34ng8zf195tHMplamEFClQ
    username: fdilekpp
    virtual-host: fdilekpp
