server:
  port: 8080
spring:
  data:
    redis:
      database: 0
      host: 703ec8c00926.c.methodot.com
      port: 31169
  datasource:
    url: jdbc:mysql://xwlin.cn:3306/iogame?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: LIAOxiang941229
    # 配置thymeleaf的相关信息
  thymeleaf:
    # 开启视图解析
    enabled: true
    #编码格式
    encoding: UTF-8
    #前缀配置
    prefix: classpath:/templates/
    # 后缀配置
    suffix: .html
    #是否使用缓存 开发环境时不设置缓存
    cache: false
    # 格式为 HTML 格式
    mode: HTML5
    # 配置类型
    servlet:
      content-type: text/html
mybatis:
  ## mybatis映射文件路径
  mapper-locations: classpath:mapping/*.xml
  ## 别名包（xml中可以不需要全路径）
  type-aliases-package: cn.xwlin.entity